# Generated by Django 6.0 on 2026-01-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mriscan',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_pdf_path',
        ),
        migrations.AddField(
            model_name='mriscan',
            name='mri_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='profile_photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='report_pdf_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
