# Generated by Django 6.0 on 2026-02-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_remove_mriscan_image_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mriscan",
            name="clinical_reasoning",
            field=models.TextField(blank=True, null=True),
        ),
    ]
